name: cloudproshield

services:
  cloudproshield:
    image: "${REGISTRY_PREFIX:-ghcr.io/jorgeturbi}/cloudproshield:${TAG:-latest}"
    container_name: cloudproshield
    restart: unless-stopped

    # Host 80 -> Contenedor 8080
    ports:
      - "80:8080"

    # Variables de la app (puedes moverlas a .env si prefieres)
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      # Si no defines PORT en .env, usará 8080
      ASPNETCORE_URLS: "http://0.0.0.0:${PORT:-8080}"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${PORT:-8080}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

    networks: [bridge]

  cloudproshield-migrator:
    image: "${REGISTRY_PREFIX:-ghcr.io/jorgeturbi}/cloudproshield-migrator:${TAG:-latest}"
    # Si es un job one-shot de migraciones:
    restart: "no"
    environment:
      DB_SERVER: 10.128.3.20
      DB_USER: sa
      DB_PASSWORD: "Brittany040238."
    # command: ["dotnet", "CloudShield.Migrator.dll", "migrate"]  # <- descomenta si aplica
    networks: [bridge]

# ✅ Declarar la red bridge del host como externa (evita "undefined network bridge")
networks:
  bridge:
    external: true
    name: bridge
