services:
  migrator:
    image: ghcr.io/jorgeturbi/cloudproshield:latest
    depends_on:
      - cloudshield
    command: ["dotnet", "CloudShield.dll", "--migrate-only"]
    environment:
      - ConnectionStrings__DefaultConnection=Server=10.128.3.20,1433;Database=CloudShield;User Id=sa;Password=Brittany040238.;Encrypt=false;TrustServerCertificate=true;
    restart: "no"

  cloudshield:
    image: ghcr.io/jorgeturbi/cloudproshield:latest
    environment:
      - RUN_DB_MIGRATIONS=false
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DefaultConnection=Server=10.128.3.20,1433;Database=CloudShield;User Id=sa;Password=Brittany040238.;Encrypt=false;TrustServerCertificate=true;
    ports:
      - "80:80"
    restart: unless-stopped
