services:
  cloudshield:
    image: ghcr.io/jorgeturbi/cloudproshield:latest
    container_name: cloudshield
    restart: unless-stopped
    ports:
      - "80:8080"
    # Cargamos variables desde .env generado por el workflow
    env_file:
      - .env
    # Si necesitas variables adicionales, usa uno de estos formatos válidos:
    # environment:
    #   ASPNETCORE_URLS: http://0.0.0.0:8080
    #   CUSTOM_FLAG: "true"
    #   TIMEOUT_SECS: "30"
    # --- o lista ---
    # environment:
    #   - ASPNETCORE_URLS=http://0.0.0.0:8080
    #   - CUSTOM_FLAG=true
    #   - TIMEOUT_SECS=30
