
services:
  cloudproshield:
    image: ghcr.io/jorgeturbi/cloudproshield:latest
    container_name: cloudproshield
    restart: unless-stopped

    # Host 80 -> Contenedor 8080
    ports:
      - "80:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      # Si no defines PORT en .env, usará 8080
      ASPNETCORE_URLS: "http://0.0.0.0:${PORT:-8080}"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${PORT:-8080}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  cloudproshield-migrator:
    image: ${REGISTRY_PREFIX}-cloudproshield-migrator:${TAG} 
    environment:
      DB_SERVER: 10.128.3.20
      DB_USER: sa
      DB_PASSWORD: "Brittany040238."
    networks: [bridge]

networks:
  default:
    driver: bridge
