// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudShield.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401035721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudShield.Entities.Role.Permissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Write",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Reader",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "View",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Delete",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Update",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CloudShield.Entities.Role.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has full access to all system features, settings, and user management. Responsible for maintaining and overseeing the platform.",
                            Name = "Administrator",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has limited access to the system, can view and interact with allowed features based on their permissions. Typically focuses on using the core functionality",
                            Name = "User",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CloudShield.Entities.Role.RolePermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionsId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("CloudShield.Entities.Users.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Entities.Users.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afganistán"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Samoa Americana"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Antártida"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Azerbaiyán"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bahrein"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bielorrusia"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Belice"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Benín"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Bután"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bosnia-Herzegovina"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Camboya"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Camerún"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Islas Caimán"
                        },
                        new
                        {
                            Id = 39,
                            Name = "República Centroafricana"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 42,
                            Name = "China"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Isla de Navidad"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Islas Cocos"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Comores"
                        },
                        new
                        {
                            Id = 47,
                            Name = "República del Congo"
                        },
                        new
                        {
                            Id = 48,
                            Name = "República Democrática del Congo"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Islas Cook"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Costa de Marfíl"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Croacia"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = 55,
                            Name = "República Checa"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 59,
                            Name = "República Dominicana"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Egipto"
                        },
                        new
                        {
                            Id = 62,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Etiopía"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Islas Malvinas"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Islas Feroe"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Finlandia"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Francia"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guyana Francesa"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Polinesia Francesa"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Tierras Australes y Antárticas Francesas"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Gabón"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Alemania"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Grecia"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Groenlandia"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Granada"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Guadalupe"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Haití"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Vaticano"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Hungría"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Islandia"
                        },
                        new
                        {
                            Id = 96,
                            Name = "India"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Irán"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Irlanda"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Italia"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Japón"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Jordania"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Kazajstán"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Kenia"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Corea del Norte"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Corea del Sur"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Kirguistán"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Letonia"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Libia"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Lituania"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Malasia"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Islas Marshall"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Martinica"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Mauricio"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 135,
                            Name = "México"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Estados Federados de Micronesia"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Moldavia"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Mónaco"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Marruecos"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Holanda"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Antillas Holandesas"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Nueva Caledonia"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Islas Norfolk"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Islas Marianas del Norte"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Omán"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Pakistán"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Palestina"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Panamá"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Papua Nueva Guinea"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Perú"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Polonia"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Reunión"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Rumanía"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Rusia"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Santa Helena"
                        },
                        new
                        {
                            Id = 177,
                            Name = "San Kitts y Nevis"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Santa Lucía"
                        },
                        new
                        {
                            Id = 179,
                            Name = "San Vicente y Granadinas"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 181,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Arabia Saudita"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Sierra Leona"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Eslovaquía"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Eslovenia"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Islas Salomón"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Sudáfrica"
                        },
                        new
                        {
                            Id = 194,
                            Name = "España"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Sudán"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Surinam"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Swazilandia"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Suecia"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Suiza"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Siria"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Taiwán"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Tadjikistan"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Tailandia"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Timor Oriental"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Trinidad y Tobago"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Túnez"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Turquía"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Islas Turcas y Caicos"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Ucrania"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Uzbekistán"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Islas Vírgenes Británicas"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Islas Vírgenes Americanas"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Wallis y Futuna"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Sáhara Occidental"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Entities.Users.Sessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireTokenRefresh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireTokenRequest")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevoke")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRefresh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Entities.Users.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Confirm = true,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jturbi@syschar.com",
                            IsActive = true,
                            Name = "Admin",
                            Password = "Lavacaloca@123",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CloudShield.Entities.Role.RolePermissions", b =>
                {
                    b.HasOne("CloudShield.Entities.Role.Permissions", "Permissions")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CloudShield.Entities.Role.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Users.User", "User")
                        .WithMany("RolePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permissions");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloudShield.Entities.Users.Address", b =>
                {
                    b.HasOne("Entities.Users.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("CloudShield.Entities.Users.Address", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Users.Sessions", b =>
                {
                    b.HasOne("Entities.Users.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Users.State", b =>
                {
                    b.HasOne("Entities.Users.Country", "Country")
                        .WithMany("State")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CloudShield.Entities.Role.Permissions", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CloudShield.Entities.Role.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Entities.Users.Country", b =>
                {
                    b.Navigation("State");
                });

            modelBuilder.Entity("Entities.Users.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("RolePermissions");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
