name: Deploy Web API to IIS on Windows Server

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.203'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the project
        run: dotnet publish -c Release -o ./publish

      - name: Stop IIS App
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "AppCloud"

      - name: Deploy to IIS
        run: |
          Remove-Item "C:\inetpub\wwwroot\Cloud\*" -Recurse -Force
          Copy-Item -Path ./publish/* -Destination "C:\inetpub\wwwroot\Cloud" -Recurse

      - name: Start IIS App
        run: |
          Start-WebAppPool -Name "AppCloud"

