name: Deploy Web API to IIS on Windows Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verificar rutas del proyecto
        run: Get-ChildItem -Recurse -Filter *.csproj

      - name: Restore dependencies
        run: dotnet restore ./CloudShield.csproj

      - name: Build the project
        run: dotnet build ./CloudShield.csproj --configuration Release

      - name: Stop IIS AppPool (only if running)
        run: |
          Import-Module WebAdministration
          $appPoolName = "AppCloud"
          $appPool = Get-WebAppPoolState -Name $appPoolName
          if ($appPool.Value -ne "Stopped") {
            Stop-WebAppPool -Name $appPoolName
          }

      - name: Clean publish folder
        run: |
          if (Test-Path ./publish) {
            Remove-Item ./publish -Recurse -Force
          }

      - name: Publish the project
        run: dotnet publish ./CloudShield.csproj --configuration Release --output ./publish

      - name: Deploy to IIS
        run: |
          $targetPath = "C:\inetpub\wwwroot\Cloud"
          if (!(Test-Path $targetPath)) {
            New-Item -ItemType Directory -Path $targetPath
          }
          Remove-Item "$targetPath\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path ./publish/* -Destination $targetPath -Recurse

      - name: Start IIS AppPool
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "AppCloud"

