name: CI/CD – CloudProSUITE (Docker on Ubuntu Server)

on:
  push:
    branches:
      - main

env:
  # Imagen fija en GHCR para este repo
  IMAGE_NAME: ghcr.io/jorgeturbi/cloudproshield
  REPO_URL: "https://github.com/JorgeTurbi/CloudProShield"

jobs:
  build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # necesario para publicar en GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        id: set_short_sha
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # ✅ CORREGIDO: Usar find en lugar de globbing
      - name: List .csproj (verificación rápida)
        run: |
          echo "=== Buscando archivos .csproj ==="
          find . -name "*.csproj" -type f -exec ls -la {} \;
          echo "=== Verificando CloudShield.csproj ==="
          ls -la CloudShield.csproj || echo "CloudShield.csproj no encontrado en raíz"

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./CloudShield.csproj

      - name: Build (Release)
        run: dotnet build ./CloudShield.csproj -c Release --no-restore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ✅ CORREGIDO: Eliminada tag duplicada
      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.set_short_sha.outputs.sha_short }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
          provenance: false

      - name: Output info
        run: |
          echo "Repo:   $REPO_URL"
          echo "Image:  $IMAGE_NAME:latest"
          echo "Image:  $IMAGE_NAME:${{ steps.set_short_sha.outputs.sha_short }}"

      - name: Build & Push Migrator (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.migrator
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}-migrator:latest
            ${{ env.IMAGE_NAME }}-migrator:${{ steps.set_short_sha.outputs.sha_short }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}-migrator:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}-migrator:buildcache,mode=max
          provenance: false

  deploy:
    name: Deploy on Ubuntu (Docker Compose)
    runs-on: self-hosted
    needs: build-and-push

    permissions:
      packages: read

    env:
      IMAGE_NAME: ghcr.io/jorgeturbi/cloudproshield

    steps:
      - name: Checkout (opcional)
        uses: actions/checkout@v4

      - name: Login to GHCR (server)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Si tu docker-compose usa :latest, con pull+up basta
      - name: Docker Compose Pull
        run: docker compose pull

      - name: Docker Compose Up
        run: docker compose up -d --remove-orphans

      - name: Show running services
        run: |
          docker compose ps
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

      # ✅ AGREGADO: Health check opcional
      - name: Wait for service to be healthy
        run: |
          echo "Esperando que el servicio esté saludable..."
          for i in {1..30}; do
            if docker compose ps | grep -q "healthy"; then
              echo "✅ Servicio saludable"
              break
            fi
            echo "Intento $i/30 - Esperando..."
            sleep 10
          done
          docker compose ps